# Generated by Django 2.1.5 on 2019-01-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ingredients.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
